FROM python:3.12-slim

WORKDIR /frontend

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "index.py"]
