FROM python:3.12-slim

WORKDIR /backend

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD [ "uvicorn", "backend:app", "--host", "0.0.0.0", "--port","8000" ]