FROM python:3.12-slim

WORKDIR /machine-learning

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "model.py"]
